// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYoxRxLyTc3ErOqbiXENewotcmLCCvVi8',
    appId: '1:1003804851680:web:f533c56157ee6404e7bf85',
    messagingSenderId: '1003804851680',
    projectId: 'flutterauthexample-429b8',
    authDomain: 'flutterauthexample-429b8.firebaseapp.com',
    storageBucket: 'flutterauthexample-429b8.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTWZ7ToPpNGsndtpdiyy2axyuK8NNVvbI',
    appId: '1:1003804851680:android:483891e4d40ae8b3e7bf85',
    messagingSenderId: '1003804851680',
    projectId: 'flutterauthexample-429b8',
    storageBucket: 'flutterauthexample-429b8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLj9F5IIzJniJ252TJmwosoDqxjsat_xI',
    appId: '1:1003804851680:ios:6fafb5d412db9004e7bf85',
    messagingSenderId: '1003804851680',
    projectId: 'flutterauthexample-429b8',
    storageBucket: 'flutterauthexample-429b8.appspot.com',
    iosClientId: '1003804851680-g4kfb4rc5lkj5b4rclp8845isse455c8.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterAuthExample',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCLj9F5IIzJniJ252TJmwosoDqxjsat_xI',
    appId: '1:1003804851680:ios:6fafb5d412db9004e7bf85',
    messagingSenderId: '1003804851680',
    projectId: 'flutterauthexample-429b8',
    storageBucket: 'flutterauthexample-429b8.appspot.com',
    iosClientId: '1003804851680-g4kfb4rc5lkj5b4rclp8845isse455c8.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterAuthExample',
  );
}
